apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  clusterIP: 10.96.0.2
  type: LoadBalancer
  ports:
  - name: testport
    port: 8000
    targetPort: 5000
    protocol: 'TCP'
  selector:
    app: rest_api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-rest-api-pod
  labels:
    app: rest_api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  selector :
    matchLabels:
      app: rest_api
  template:
    metadata:
      labels:
        app: rest_api
    spec:
      volumes:
        - name: my-hostpath-volume
          hostPath:
            path: /d/REST_API_TEST2/k8s_flask
            type: Directory
      containers:
      - name: flask-sora
        image: charmingsora12/model_rest_api
        imagePullPolicy: Always
        env:
        - name : MODEL_NAME
          value: "test_model"
        - name : MODEL_TYPE
          value: "tf"
        - name : MY_HOST_NAME
          value: "000.000.000"
        - name : MY_USER_NAME
          value : "d0106"
        - name : MY_PASSWORD
          value : "d0106!@#$"
        - name : AZURE_STORAGE_CONNECTION_STRING
          value : "DefaultEndpointsProtocol=_"
          
        volumeMounts:
          - name: my-hostpath-volume
            mountPath: /root/model_rest_api
        ports:
        - containerPort: 5000
        command: ["/bin/sh","-c"]
        args: ["sh start_celery.sh && tail -f /dev/null"]
